version: 2.1
executors:
  firestore:
    docker:
      - image: circleci/openjdk:stretch-node-browsers-legacy
  default:
    docker:
      - image: "circleci/node:latest"
jobs:
  format_check:
    executor:
      name: default
    steps:
      - checkout
      - run:
          command: npm install
      - run:
           command: npx prettier -c packages/**/*.ts packages/**/*.tsx
  test:
    executor:
      name: default
    steps:
      - checkout
      - run:
          command: npm install
      - run:
          command: npx lerna bootstrap
      - run:
          command: npx lerna run test
  middle_test:
    executor:
      name: firestore
    steps:
      - checkout
      - run:
          command: npm install
      - run:
          command: npx lerna bootstrap
      - run:
          command: "npx firebase setup:emulators:firestore"
      - run:
          name: Starup firestore emulator
          command:
            java -jar $HOME/.cache/firebase/emulators/cloud-firestore-emulator-v1.3.0.jar --host=127.0.0.1
          background: true
      - run:
          command: "npx lerna run test:middle"
workflows:
  check:
    jobs:
      - format_check
      - test
      - middle_test
