version: 2.1
executors:
  firestore:
    docker:
      - image: circleci/openjdk:stretch-node-browsers-legacy
  default:
    docker:
      - image: circleci/openjdk:stretch-node-browsers-legacy
jobs:
  lint:
    executor:
      name: default
    steps:
      - checkout
      - run:
          command: npm install
      - run:
           command: npx prettier -c packages/**/*.ts packages/**/*.tsx
      - run:
          command: npm run lint
  test:
    executor:
      name: default
    steps:
      - checkout
      - run:
          command: npm install
      - run:
          command: npx lerna bootstrap --ignore=@bkmk/firestore
      - run:
          command: npx lerna run build --scope @bkmk/core @bkmk/browser
      - run:
          command: npx lerna run build --scope @bkmk/browser
      - run:
          command: npx lerna run test --ignore=@bkmk/firestore
  middle_test:
    executor:
      name: firestore
    steps:
      - checkout
      - run:
          command: npm install
      - run:
          command: npx lerna bootstrap --concurrency 2
      - run:
          command: "npx firebase setup:emulators:firestore"
      - run:
          name: Starup firestore emulator
          command:
            java -jar $HOME/.cache/firebase/emulators/cloud-firestore-emulator-*.jar --host=127.0.0.1
          background: true
      - run:
          command: "npx lerna run test:middle"
workflows:
  check:
    jobs:
      - lint
      - test
      - middle_test
